import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "dp project ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="border-b border-gray-300 w-screen ">
          <div className="flex justify-between px-10 py-2">
            <h1 className="text-xl ">App</h1>
            <div>
              <button className="px-4 py-2 rounded-md bg-blue-500 hover:bg-blue-600 ">
                Logo out
              </button>
            </div>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
